/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.packages;


import org.jooq.impl.PackageImpl;
import org.jooq.mcve.java.Devsb;


/**
 * Convenience access to all stored procedures and functions in TYPES
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Types extends PackageImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEVSB.TYPES</code>
     */
    public static final Types TYPES = new Types();

    /**
     * No further instances allowed
     */
    private Types() {
        super("TYPES", Devsb.DEVSB);
    }
}
