/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.packages.types.udt.records;


import java.util.Arrays;
import java.util.Collection;

import org.jooq.impl.ArrayRecordImpl;
import org.jooq.mcve.java.Devsb;
import org.jooq.mcve.java.packages.Types;



/**
 * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAssociativearrayRowRecord extends ArrayRecordImpl<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new <code>DEVSB.TYPES.T_ASSOCIATIVEARRAY_ROW</code> record
     */
    public TAssociativearrayRowRecord() {
        super(Devsb.DEVSB, Types.TYPES, "T_ASSOCIATIVEARRAY_ROW", org.jooq.impl.DefaultDataType.getDefaultDataType("\"DEVSB\".\"MCVETEST%ROWTYPE\""));
    }

    /**
     * Create a new <code>DEVSB.TYPES.T_ASSOCIATIVEARRAY_ROW</code> record
     */
    public TAssociativearrayRowRecord(Object... array) {
        this();
        if (array != null)
            addAll(Arrays.asList(array));
    }

    /**
     * Create a new <code>DEVSB.TYPES.T_ASSOCIATIVEARRAY_ROW</code> record
     */
    public TAssociativearrayRowRecord(Collection<? extends Object> collection) {
        this();
        addAll(collection);
    }
}
