/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.packages.types.udt.records;


import org.jooq.impl.AssociativeArrayRecordImpl;
import org.jooq.impl.SQLDataType;
import org.jooq.mcve.java.Mcve;
import org.jooq.mcve.java.packages.Types;
import org.jooq.mcve.java.tables.records.McvetestRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAssociativearrayRowRecord extends AssociativeArrayRecordImpl<String, McvetestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new <code>MCVE.TYPES.T_ASSOCIATIVEARRAY_ROW</code> record
     */
    public TAssociativearrayRowRecord() {
        super(Mcve.MCVE, Types.TYPES, "T_ASSOCIATIVEARRAY_ROW", org.jooq.mcve.java.tables.Mcvetest.MCVETEST.getDataType(), SQLDataType.VARCHAR);
    }
}
