/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.packages.types.udt.records;


import org.jooq.impl.AssociativeArrayRecordImpl;
import org.jooq.impl.SQLDataType;
import org.jooq.mcve.java.Mcve;
import org.jooq.mcve.java.packages.Types;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAssociativearrayRecord extends AssociativeArrayRecordImpl<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new <code>MCVE.TYPES.T_ASSOCIATIVEARRAY</code> record
     */
    public TAssociativearrayRecord() {
        super(Mcve.MCVE, Types.TYPES, "T_ASSOCIATIVEARRAY", SQLDataType.VARCHAR(240), SQLDataType.VARCHAR);
    }
}
