/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java.packages.types.udt.records;


import java.util.Arrays;
import java.util.Collection;

import org.jooq.impl.ArrayRecordImpl;
import org.jooq.impl.SQLDataType;
import org.jooq.mcve.java.Devsb;
import org.jooq.mcve.java.packages.Types;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAssociativearrayRecord extends ArrayRecordImpl<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new <code>DEVSB.TYPES.T_ASSOCIATIVEARRAY</code> record
     */
    public TAssociativearrayRecord() {
        super(Devsb.DEVSB, Types.TYPES, "T_ASSOCIATIVEARRAY", SQLDataType.VARCHAR(240));
    }

    /**
     * Create a new <code>DEVSB.TYPES.T_ASSOCIATIVEARRAY</code> record
     */
    public TAssociativearrayRecord(String... array) {
        this();
        if (array != null)
            addAll(Arrays.asList(array));
    }

    /**
     * Create a new <code>DEVSB.TYPES.T_ASSOCIATIVEARRAY</code> record
     */
    public TAssociativearrayRecord(Collection<? extends String> collection) {
        this();
        addAll(collection);
    }
}
