/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.mcve.java.tables.Mcvetest;
import org.jooq.mcve.java.tables.records.McvetestRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * MCVE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<McvetestRecord> PK_TEST = Internal.createUniqueKey(Mcvetest.MCVETEST, DSL.name("PK_TEST"), new TableField[] { Mcvetest.MCVETEST.ID }, true);
}
