/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.java;


import org.jooq.mcve.java.tables.Mcvetest;


/**
 * Convenience access to all tables in MCVE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>MCVE.MCVETEST</code>.
     */
    public static final Mcvetest MCVETEST = Mcvetest.MCVETEST;
}
